baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "fuji"
destination = "./public"


[markup.asciidocext]
    args = ["--no-header-footer", "-r", "asciidoctor-html5s", "-b", "html5s", "-r", "asciidoctor-diagram"]
    workingFolderCurrent = true
